---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: webapp-backend-production
  namespace: gotk-system
spec:
  healthChecks:
  - kind: Deployment
    name: backend
    namespace: production
  interval: 10m0s
  path: ./deploy/overlays/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: webapp-backend
  timeout: 2m0s
  validation: client

